subscription_name      = "1bff8c1b-951f-4dce-9a24-8553ddcc442b"
rg_name                = "CYTSP5TSTRGCIN001"
windows_vm_name        = "CYTSP5TVMCIN001"               
monitor_ag_name            = "emailalert"
monitor_activity_log_alert_name      = "VM-service-health"
monitor_activity_log_alert_category  = "ResourceHealth"
monitor_activity_log_alert_operation = "Microsoft.Resourcehealth/healthevent/Activated/action"