rg_name        = "CYTSP5TSTRGCIN001"
location       = "Central India"
storageaccount_name = "cytsp5sargcin001"
nsg_name       = "CYTSP5TSTNSGCIN001"
log_analytics_workspace_name = "vm-law-dev-cin-001"
network_watcher_name     = "Network-Watcher-CIN"
network_watcher_log_name = "Network-Watcher-Logs"