windows_vm_name = "CYTSP5TVMCIN001"
rg_name         = "CYTSP5TSTRGCIN001"
rsv_name        = "CYTSP5TSTRSVCIN001"
location        = "Central India"
rsv_sku         = "Standard"
rsv_policy_name = "CYTSP5TSTBCPCIN001"